package uk.nhs.digital.uec.api.domain;

public enum FilterType {
    BOOLEAN_VALUE,
    STRING_EXACT_MATCH,
    STRING_CASE_INSENSITIVE_LIKE,
    JOIN_BY_CODE,
    LINKED_BOOLEAN_VALUE,
    LINKED_STRING_EXACT_MATCH,
    LINKED_STRING_CASE_INSENSITIVE_LIKE,
    LINKED_JOIN_BY_CODE,
    DATE_EXACT_MATCH,

}
